### ISSUE TITLE
Frontend tests for DB calls

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#102]
Some spec and end to end tests for the DB calls functionality must be implemented.

**Comment by AlbertFX91** [comment]
## Karma
I've created a test which it run the properties function if we have an array or a single data.
fe575663877f1512b9b80b86e74799dcadbc8bdb
[Result](https://gyazo.com/e272c4fbebc4618b11c59b11bf21b88d)
## Protractor
Some nice tests running queries and connections. It test the list view and the detail as well
02ef54ac167e29faea451fc299e84a5bd7fa33f2
[Result](https://gyazo.com/fff11e5eb69ee454c214afc83953987c)

**Comment by juagarfer4** [comment]
Sounds good to me!
