### ISSUE TITLE
API REST - Error with a json key

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#112]
When the API REST module wants to map a key data which its a json itself, an internal server error is ocurred.
Use as example https://jsonplaceholder.typicode.com/users

**Comment by juagarfer4** [comment]
We'll leave it like this for the moment then:

ef6ed09
[Demo](https://gyazo.com/7a5585d35ffaa67e1158f5259a0f9c9c)

**Comment by AlbertFX91** [comment]
Perfect bro :D
