### ISSUE TITLE
Exceptions handling

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#125]

**Comment by juagarfer4** [comment]
The handling of exceptions must be implemented in this module.

**Comment by juagarfer4** [comment]
Thank you so much, Al! And shout out to Pedro.

Source: 938cce3
Demo: [(1)](https://gyazo.com/8a20d367d7934c7930ae810ff2f1d017) [(2)](https://gyazo.com/d3ee84ee66053f0bbe179ab1b5cf144d)

**Comment by AlbertFX91** [comment]
Nice one bro!
