### ISSUE TITLE
Get the PK of a table

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#126]

**Comment by juagarfer4** [comment]
It is necessary to get the primary key of a table.

**Comment by AlbertFX91** [comment]
Done dude! 
It was a hard work but finally is done. But you know what? I have done the #127 too.
[Demo](https://gyazo.com/a75136438343ca7b86e5afd328d92728)
[Data structure](https://gyazo.com/4551ab1e974a2597e61edee1a6ad1ce7)
