### ISSUE TITLE
Getting deeper with Angular 4

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#14]
Before doing this task, please finish the task #12 

Angular 4 has a lot of components and modules, and it works with Typescript. You need to study and do all the exercises which appears in the next material attached.

https://www.youtube.com/watch?v=YVVjXpquzBE

Please, be honest doing all the exercises before consult the solution.

To get the task done, it's necessary to show the exercise or exercises running in a gif.

**Comment by juagarfer4** [comment]
Finally:

EXERCISE 1:
https://gyazo.com/d4c539de35179c6cfd60d9072c05a48c
EXERCISE 2:
https://gyazo.com/fa7645a595c2f759123c3e66c2661037
https://gyazo.com/2b5db688a4057a739feb03a007e972f1
EXERCISE 3:
https://gyazo.com/864a0db9561ef81809a0ad2fffb60db8
https://gyazo.com/d00fcfd800815cd93ed43354486395fd
EXERCISE 4:
https://gyazo.com/c9066384ca1843f1ef917a792ae01c5a
https://gyazo.com/376427970925257e113108b0ac06dc12
EXERCISE 5:
https://gyazo.com/367e70bf4fb325396ce7632f75a70efd
https://gyazo.com/e92494f54b5e316e316d7ac1e5bc9a8d
https://gyazo.com/8617afd527192cad99f593bcd0fbd11d

**Comment by AlbertFX91** [comment]
Nice work bro! And the checking of the items works! Really nice one
