### ISSUE TITLE
Add control variable input in frontend and send to backend

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#144]

**Comment by AlbertFX91** [comment]
Hi!
9682b540e389cf5e8f3bea47e73c6782cdcdd258
I've done it in the sql.component in a different form, but its been desplayed when we make a connection 💃 
[Demo](https://gyazo.com/f03a355e4ec34264add211c80bb037d4)

**Comment by juagarfer4** [comment]
I like it that way!
