### ISSUE TITLE
Create method for SQLDataRecover in SQLResource

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#145]

**Comment by AlbertFX91** [comment]
11dd25550c211d87e753365c331c3521bd0c3ddc
I've added a new method in the SQLResource.
I think in the future we're going to need a new resource which it will be for a generic type <T>, but just for now i think its a good aproximation
[Demo](https://gyazo.com/60dd30c4b3f56a075a338f95363557fb)

**Comment by juagarfer4** [comment]
Yeah I agree, we could work with an unique resource for both kinds of data recoveries. We'll see about that later on.
