### ISSUE TITLE
Getting deeper with Angular 4

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#15]
Before doing this task, please finish the task #13 

Angular 4 has a lot of components and modules, and it works with Typescript. You need to study and do all the exercises which appears in the next material attached.

https://www.youtube.com/watch?v=YVVjXpquzBE

Please, be honest doing all the exercises before consult the solution.

To get the task done, it's necessary to show the exercise or exercises running in a gif.

**Comment by AlbertFX91** [comment]
Here is all the exercises done!

- [x] [Exercise 1](https://gyazo.com/ab0ff9b112abed60ec82498e88623daa)
- [x] [Exercise 2](https://gyazo.com/9a094f3943aba271a8bb070c2fa6bec7)
- [x] [Exercise 3](https://gyazo.com/dfe680820efc71ffc6922cd2c7a72f58) The update doesnt work with all the code copied :/
- [X] [Exercise 4](https://gyazo.com/ad6119943b3fd58f8ff2604afdedb838) The same as Exercise 3
- [X] Exercise 5 🥇 
   - [Create and list books](https://gyazo.com/60da49f6f0c5c0637e7ed690c1be2d3b)
   - [Edit book](https://gyazo.com/591e6010bb59dd5b706951b3b3819eb1)
   - [Remove book](https://gyazo.com/f4a14da5bb2f7e9ea4df038498c6006c)

**Comment by juagarfer4** [comment]
That was some awesome job, like you always do. I trully mean it.
