### ISSUE TITLE
Save SQLControlVar with SQLConnection (service and repository)

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#152]

**Comment by AlbertFX91** [comment]
Done! There are a lot of bugs with the queries but its a good aproximation.
b776ae243e0660ea716f188e07f0ee4b8b8d3a5f
1886fdcc91c7cab633b1aa601057f765e36a7773
[Demo](https://gyazo.com/bb25c78a25d2bd3edadf7a3e4a34ad1c)
