### ISSUE TITLE
UI - Service static cv_cords

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#171]

**Comment by juagarfer4** [comment]
I added some other stuff as well, but the point of this issue was the service, which is pretty useless just by itself lol.

Source: 1f9e765

**Comment by AlbertFX91** [comment]
You know, the cv_cards static structure its not a perfect one because they are in a tree structure grouped by status. I know we have talked about it and it will be edited in the next issues :D
