### ISSUE TITLE
Perform monitoring

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#190]

**Comment by AlbertFX91** [comment]
Data monitoring in Core version Done!
It was necessary to remove the scheduling jobs from the last version. So if you create a control var from our first static version, it wont be monitored
[Data structure](https://gyazo.com/a3ba269b5409f5ffe3403e5b78b554e8)
To test it:

1. Run the server
2. Go to API
3. Launch get /api/controlvar/create 
4. Go to Robomongo and/or eclipse console
5. Check the monitoring is real!

**Comment by juagarfer4** [comment]
Yes, indeed! Core control vars are being monitoreed.
