### ISSUE TITLE
Calling monitoring method dynamically

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#201]

**Comment by AlbertFX91** [comment]
https://stackoverflow.com/questions/37344801/spring-scheduler-parallel-running
https://stackoverflow.com/questions/14630539/scheduling-a-job-with-spring-programmatically-with-fixedrate-set-dynamically
https://stackoverflow.com/questions/17669445/java-example-dynamic-job-scheduling-with-quartz

+ Tasks throw in parallel: https://docs.spring.io/spring/docs/3.1.x/javadoc-api/org/springframework/scheduling/annotation/EnableScheduling.html
+ Creation scheluded tasks with reflection: https://stackoverflow.com/questions/31117970/how-to-schedule-different-java-classes-dynamically
