### ISSUE TITLE
Including monitoring time in forms

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#204]

**Comment by AlbertFX91** [comment]
e3c97a0058051fdca3d65da62ba0e214efb164ae 7b1ce2fd1b64d51bca92dbfb8bdc5b1f81710ca6
Yo bro, that really was a piece of cake 💃 

[SQL](https://gyazo.com/7e3bd2719d740cd4a043aa88864a2927)
[REST](https://gyazo.com/47d7032a5ac266db380dba0d7bda77bb)
