### ISSUE TITLE
Restart scheduled tasks when a ControlVar is created

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#209]

**Comment by AlbertFX91** [comment]
Yeah! It works! 
It was necessary to change all the structure from the last version. Now, we have a service which register the jobs, readed from the database. 

Now, we can stop scheduled jobs and create new ones in runtime. In the previous version, the scheduled jobs were launched when the server started and the jobs were unreachable to cancel and create new ones.

Now, we have a powerfull structure to manage our scheduled jobs! Hell yeah!

To test it:
- Launch the populate database
- Launch the app
- Check the controlvars and check that they are updated
- Create a new controlvar from our awesome UI
- Check the new controlvar in DB and how it's updated!

**Comment by juagarfer4** [comment]
I have been reviewing it following your instructions and I gotta say, this is top notch! This is just what we needed. Very good work!
