### ISSUE TITLE
One entry resource point for n control vars

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#234]

**Comment by AlbertFX91** [comment]
c78d20c3ed9b4e8c64855e75a56209b6b1dc1ece
First version of a generic controller to create controlvars. It is not the best solution because the connection data must be a map of strings in another attribute, plus the connectionClass name.

A developer friendly version will be studied soon

**Comment by AlbertFX91** [comment]
Well, I have not found another better way to solve our problem.
There is an [example body](https://gyazo.com/72ea53c2e33e8a3cd2987f3582779e2f) request to test our resource.

**Comment by juagarfer4** [comment]
Maybe it is not the nicest of the solutions, but at least now we have a way to create control vars using the new core implementation that is unique for both REST and SQL control vars. So far, so good!
