### ISSUE TITLE
REST - Request permission to Facebook

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#254]

**Comment by juagarfer4** [comment]
Turns out I was confusing application with page. Please kill me.

[Demo](https://gyazo.com/6704beda13555e239bc776ffec186464)

**Comment by juagarfer4** [comment]
Turns out I was confusing application with page. Please just kill me.

[Demo](https://gyazo.com/6704beda13555e239bc776ffec186464)
