### ISSUE TITLE
Frontend - Font style on global.css (Roboto)

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#263]

**Comment by juagarfer4** [comment]
Roboto looks nice indeed!

[Source](https://gyazo.com/3c76f9db0c7188bbd409a8b41a50d239)

**Comment by juagarfer4** [comment]
Roboto looks nice indeed!

[Demo](https://gyazo.com/3c76f9db0c7188bbd409a8b41a50d239)

**Comment by AlbertFX91** [comment]
OMG! I ❤️ DECCOM!
