### ISSUE TITLE
Error with application.yml

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#274]
To be defined
1. Get the application.yml file back with wrong API KEYS VALUES

**Comment by juagarfer4** [comment]
Just tracked application.yml again, but with wrong application values. You know how to find the good ones!

**Comment by juagarfer4** [comment]
OK, so now it is done! The file application.yml is tracked with wrong application values, but its changes will be ignored for commits (until we decide otherwise, of course). Now we will be able to use the true values in the application without fear of committing them.
