### ISSUE TITLE
Module file Game

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#31]
Its necessary to implement:
- Module file
- Router file
- index.ts
- Sample component with a print
This is very useful to check that all the configuration is perfect :)

**Comment by juagarfer4** [comment]
With a little help from my friend(s):
https://gyazo.com/66ec4d17bd109621d1daa0c7eb7768d2
https://gyazo.com/109ab218b1ae622d3fd756ccf8f9135c
https://gyazo.com/3b9ba73a21d9096f5e7fd220d67ac13e
https://gyazo.com/1fd5d327ac413667e45f2d08397e4440
https://gyazo.com/90e770c5c6e5fe849c3292c1bd1165c3
https://gyazo.com/dbec8db8b43f0a92a8921fec2d2d18d7

**Comment by AlbertFX91** [comment]
Ctrl + F5 is your friend!
