### ISSUE TITLE
Module file Game

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#38]

**Comment by AlbertFX91** [comment]
It was necessary to create a route and a sample component to check the module and its inclusion in the project :D 
- [game.module.ts](https://gyazo.com/cc27828cf16d12ebabe38f3b1b3cf24b)
- [game.route.ts](https://gyazo.com/9689562f717faf85d5031a3ccf6ff30d)
- [Working](https://gyazo.com/7592c0194eae98c7b223a667812ada44)

**Comment by juagarfer4** [comment]
Shout out to Micael Gallego!
