### ISSUE TITLE
Details game

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#46]
Its necessary to make a view with all the data of a game displayed 👍

**Comment by juagarfer4** [comment]
I'm not commenting anymore in this sprint bruh haha.

[Code](https://gist.github.com/juagarfer4/e2bbfa5a08867b83e8e9bf007b83c700)
[Living proof](https://gyazo.com/8f927f76bf627c722de4a79a8b0ed69b)

**Comment by AlbertFX91** [comment]
Yo bro, why the URL is not displayed in the living proof? :/
Check it out and why dont u use a 'a href' node instead? :D

**Comment by juagarfer4** [comment]
I added URL as an optional attribute and then decided not to include any URLs when populating lol. I can create a new game with an URL just to check.

**Comment by AlbertFX91** [comment]
You know, it's a good practice if you have an optional attribute to add examples in both cases, because now you don't really now if it's works! but I'll close it!
