### ISSUE TITLE
Delete game

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#48]
This task consist in add the delete functionality in the game list. 
The default project uses a popup/modal to implement it, so just to simplify the task, add a function in the 'click' event, and use the code generated in the popup-service example. 
In the function, use the ['confirm(msg)' window](https://www.w3schools.com/jsref/met_win_confirm.asp) method to get a verification from the user

**Comment by juagarfer4** [comment]
Sometimes the easiest way is the best way.

https://gyazo.com/79d3712f84f3baabe4a6241a6c9f7d93

**Comment by AlbertFX91** [comment]
Nice solution! :D
