### ISSUE TITLE
Frontend - Tests [Spec+ e2e]

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#52]
Do not do the Gatling tests. Gatling is for performance and is not part of the frontend.
- Spec tests: Execute yarn test
- e2e:
  - (INSTALATION) npm install -g protractor
  - (INSTALATION) webdriver-manager update
  - Run: go to the folder 'src/test/javascript/' and run 'protractor'

**Comment by juagarfer4** [comment]
It works!

Basically, the e2e test was trying to open the games list through the upper navbar in the app, but the link to Games in the Entities menu must be included before. This includes adding a small line in both global.json files in the folders en and es in the i18n folder. Regarding the Game dialog, we should make sure that the actual button is called properly in the test.

[Code](https://gist.github.com/juagarfer4/95fa483862dd86c1ddd81b2017152414)
Proof [(spec)](https://gyazo.com/925659b87d3bdd04cad0004e0268946d) [(e2e)](https://gyazo.com/d59875d961294fc8d4e5722ede0562a7)
