### ISSUE TITLE
Service - Sample API REST call

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#60]
Sample API REST data: https://jsonplaceholder.typicode.com/

**Comment by juagarfer4** [comment]
Quite basic first attempt to send a HTTP GET request:

[Code](https://gist.github.com/juagarfer4/4d3ff1f5c697af25e89f86b3396cc0e1)
[Proof](https://gyazo.com/42fbb4d76e81db5a8a44f5f9e80cadb5)

**Comment by AlbertFX91** [comment]
@juagarfer4 nice work bro! its a nice aproximation. I'll close the issue but we need a data structure to get the data, instead of a list of strings. Do it for the next issue 👍
