### ISSUE TITLE
Service - API REST call without class mapping

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#62]

**Comment by juagarfer4** [comment]
So, I decided to stop working with the Books API, as I thought the JSONPlaceholder format would be more generic. Also, the Books API uses the same port as JHipster, which finally convinced me to stop using it.

Anyway, I think that using class mapping is the best solution, but both could be considered, of course.

[Source](https://gist.github.com/juagarfer4/ca8a86430b85996ed0f3861e42e78e41)
[Proof](https://gyazo.com/710442a0e8e289752d0e095c72439b71)
