### ISSUE TITLE
Service - Sample call to database

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#69]

**Comment by AlbertFX91** [comment]
Here is bro!
[Source](https://gist.github.com/AlbertFX91/bfa2197d6fe1f1ae6dc5756c4f5a7c56)
[Demo](https://gyazo.com/ea9f8913d201410a925f5559e40a337f)

**Comment by juagarfer4** [comment]
That is very good! As we just discussed, we now need to map all that info into a proper structure. Anyway, so far so good!
