### ISSUE TITLE
Service - Call to database with class mapping

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#70]

**Comment by AlbertFX91** [comment]
Done!
I've created a class model  Author and i've got all the data by the column name manually, instead of looping it like the nomapping version. Now we can see de data model in swagger!
[Source](https://gist.github.com/AlbertFX91/a020066d89d824b0b8d366eaaa413f9e)
[Demo](https://gyazo.com/efc17dc315317d8403bf231552886243)

**Comment by juagarfer4** [comment]
Yeah, I would say that this is definitely a better option that not using class mapping, specially considering that we'll have to display the data in the front-end sometime in the (very) near future.

Great job!
