### ISSUE TITLE
Service - Call to database without class mapping

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#71]

**Comment by AlbertFX91** [comment]
Hi! This is the same as the sample call because I tried to do it as general as posible.
A Json its basically a list of documents, and a document is a map Key-Value. 
So, because we dont want in this example a class mapping, I've used a list of maps to parse de data from the database to simulate a json structure. It's nice because we can use all the map's functions which had been used by us for a long time 
[Source](https://gist.github.com/AlbertFX91/c94be42ca67fccb581dfa7edcca44f5b)
[Demo](https://gyazo.com/90558b85dea12b8a7f562f8cc252f9e2)

**Comment by juagarfer4** [comment]
Mhm... as far as my research goes, I'm leaning towards using class mapping (I don't know about you), but we'll see. Anyway, this is a great aproximation to not creating a Type for the data!
