### ISSUE TITLE
Backend - Refactor server code 

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#81]

**Comment by AlbertFX91** [comment]
Nailed it! I've refactor the code and i've analized that the extraction data is composed in this steps:
- Check driver
- Connection
- Query
- Collect data
Maybe this abstraction can be useful in a future
[Code](https://gist.github.com/AlbertFX91/0d0a94f585cb852cd319b9c478ccb92c)

**Comment by juagarfer4** [comment]
Just to clarify, aren't you using the JHipster service implementation with the interface and then the class service implementing it?

**Comment by AlbertFX91** [comment]
No lol, i forget it xD But it's fixed here! a5916059b674989364d262628e1da1464401bf00

**Comment by juagarfer4** [comment]
Yay! Gotta say, I found that idea of yours for the non-mapping call quite useful. Very good!
