### ISSUE TITLE
Check if String response is JSONArray or JSONObject

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#85]

**Comment by juagarfer4** [comment]
[Source](https://gist.github.com/juagarfer4/b1201ddf7f0fada3e2ae5077a7de2313)
Demo [(single)](https://gyazo.com/b2fe0c9a5fe29fd0df368c5b0bb3852e) [(array)](https://gyazo.com/5816a57f68661ed318069e935b66bc3d)

**Comment by AlbertFX91** [comment]
Nice bro! 
But please! Change the if conditions to `if (checkResponse(response))` instead of `if (checkResponse(response) == true)`

Close the issue after do it :D
