### ISSUE TITLE
Fix XAMPP connection to database

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#86]

**Comment by juagarfer4** [comment]
OK, it seems like there was an issue with the way the user "developer" was created. 'localhost' had to be specified as the server.

[Source](https://github.com/AlbertFX91/Deccom/commit/5348cc83db3ff823f4511008b30326934f85c1fe)
[Demo](https://gyazo.com/9b5e735c69ee589889bdabe759ef1b25)

Anyway, I think that it's better to work with MySQL properly, so I'll proceed to install it.

**Comment by AlbertFX91** [comment]
Nice bro! Anyway its good to know XAMPP works!
