### ISSUE TITLE
New param: String URL

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#87]
The URL to send the request must be a param of the methods noMapping and mapping in APIRestCallsService.

**Comment by juagarfer4** [comment]
As it wasn't necessary to create a new type for the parameter, it was not a big deal.

[Source](https://github.com/AlbertFX91/Deccom/commit/5348cc83db3ff823f4511008b30326934f85c1fe)
[Demo](https://gyazo.com/490745123eab12faa84ccca33b849cc2)

To test it, please switch to the 'api-rest-calls' branch, check the API and, for the non-mapping or mapping version, introduce this URL as a parameter:

https://jsonplaceholder.typicode.com/posts

**Comment by AlbertFX91** [comment]
Perfect! :D
