### ISSUE TITLE
Form with the URL input

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#88]
A form must be created where the user can introduce the URL to request the JSON from.

**Comment by juagarfer4** [comment]
Dunno if you need to look at it that much but anyway:

Source: a8ed4dd c9b9dc1 5b39cff de4c4d4 1eeb03e
[Demo](https://gyazo.com/418713eb8b2250d7d44a94a397a385f6)

**Comment by AlbertFX91** [comment]
Perfect bro!
