### ISSUE TITLE
Frontend tests for API REST calls

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#92]
Some spec and end to end tests (Karma.js and Protractor) must be created for the API REST calls functionality.

**Comment by juagarfer4** [comment]
F** spec tests. I'm not even sorry.

For the spec tests, I'm just cheking that, after getting the JSON response, the onSuccess function that displays it does not contain an empty value or something.

Meanwhile, for the e2e tests, I send to GET requests, with one getting a JSON array and the other a single JSON as a result.

9f957c5 b9ef77f bae757e (bae lol as if I had one)
Demo [(spec)](https://gyazo.com/cee05e3f728f553a0d7aee2a8af9a557) (nevermind the errors shown, it's because of the format of the JSON response) [(e2e)](https://gyazo.com/0bbda647f7293f33e9f67499511bd38d)

**Comment by AlbertFX91** [comment]
Perfect bro!
Awesome the bae commit
