### ISSUE TITLE
Implement URL, user, pass and query as args

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#94]
For the database calls, the URL, user, pass and query must be implemented as args.

**Comment by AlbertFX91** [comment]
Done! 
88e5f2be8611d047310956546845658ac1e86173 6632821c1ea116d02aa7fd64d9b4806b1f8998ca
I've created a new class called DBQuery which contains all the necessary data to connect and query to a database.

To try it, go to our awesome swagger API tester, go to the db-calls query operation and add al the necessary data.
- username: developer
- password: developer
- url: jdbc:mysql://localhost:3306/deccom
- query: select * from author

Here is the [Demo](https://gyazo.com/2f038cc2c5f6ec73e481e189772dbf46)

**Comment by juagarfer4** [comment]
OK, so after fixing the XAMPP issue I switched to branch 'db-calls', introduced the parameters and... it works! Great then.
