### ISSUE TITLE
DB calls - Frontend - List

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#97]
A list to display the data after performing a database call must be implemented.

**Comment by AlbertFX91** [comment]
Done!
0abae6e1635061be355b4077050933756abb1622
I've make a general table which list the data by the keys of the objects. Its a generic table so it can be used for any array of objects!
[Demo](https://gyazo.com/2312eff27d111cb95be848c1a0c7645e)

**Comment by juagarfer4** [comment]
Dat's gud! Now it should be considered if there's only one object in the array so it can be displayed on its own. I'm guessing that we should return the same from *.component.ts and that it will all be implemented in *.component.html.
